# Generated by Django 4.2.3 on 2023-07-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_education_degree_alter_education_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ManyToManyField(to='api.social'),
        ),
    ]
