# Generated by Django 4.2.3 on 2023-07-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_social_user_social_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='api.social', verbose_name='socials'),
        ),
    ]
