# Generated by Django 4.2.3 on 2023-07-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_educations_remove_user_experiences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
