# Generated by Django 4.2.3 on 2024-07-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_project_role_alter_education_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_order',
            field=models.IntegerField(null=True),
        ),
    ]
